data_to_approaches = {
    "blimp": [
        # {approach}__{template}
        "ll",
        "ll_normalized",
        "ll_pen",
        "ll_intemplate_single__template_blimp_single_1",
        "ll_intemplate_single__template_blimp_single_2",
        "ll_intemplate_single__template_blimp_single_3",
        "ll_intemplate_single__template_blimp_single_4",
        "ll_intemplate_single__template_blimp_single_5",
        "ll_intemplate_single_normalized__template_blimp_single_1",
        "ll_intemplate_single_normalized__template_blimp_single_2",
        "ll_intemplate_single_normalized__template_blimp_single_3",
        "ll_intemplate_single_normalized__template_blimp_single_4",
        "ll_intemplate_single_normalized__template_blimp_single_5",
        "ll_intemplate_single_pen__template_blimp_single_1",
        "ll_intemplate_single_pen__template_blimp_single_2",
        "ll_intemplate_single_pen__template_blimp_single_3",
        "ll_intemplate_single_pen__template_blimp_single_4",
        "ll_intemplate_single_pen__template_blimp_single_5",
        "ll_intemplate_compar__template_blimp_compar_1",
        "ll_intemplate_compar__template_blimp_compar_2",
        "ll_intemplate_compar__template_blimp_compar_3",
        "ll_intemplate_compar__template_blimp_compar_4",
        "ll_intemplate_compar__template_blimp_compar_5",
        "prompting__template_blimp_ab_1",
        "prompting__template_blimp_ab_2",
        "prompting__template_blimp_ab_3",
        "prompting__template_blimp_ab_4",
        "prompting__template_blimp_ab_5",
        "prompting__template_blimp_ab-chat_1",
        "prompting__template_blimp_ab-chat_2",
        "prompting__template_blimp_ab-chat_3",
        "prompting__template_blimp_ab-chat_4",
        "prompting__template_blimp_ab-chat_5",
        "prompting_yn__template_blimp_yn_1",
        "prompting_yn__template_blimp_yn_2",
        "prompting_yn__template_blimp_yn_3",
        "prompting_yn__template_blimp_yn_4",
        "prompting_yn__template_blimp_yn_5",
        "prompting_yn__template_blimp_yn-chat_1",
        "prompting_yn__template_blimp_yn-chat_2",
        "prompting_yn__template_blimp_yn-chat_3",
        "prompting_yn__template_blimp_yn-chat_4",
        "prompting_yn__template_blimp_yn-chat_5",
    ],
    "climp": [
        "ll",
        "ll_normalized",
        "ll_pen",
        "ll_intemplate_single__template_climp_single_1",
        "ll_intemplate_single__template_climp_single_2",
        "ll_intemplate_single__template_climp_single_3",
        "ll_intemplate_single__template_climp_single_4",
        "ll_intemplate_single__template_climp_single_5",
        "ll_intemplate_single_normalized__template_climp_single_1",
        "ll_intemplate_single_normalized__template_climp_single_2",
        "ll_intemplate_single_normalized__template_climp_single_3",
        "ll_intemplate_single_normalized__template_climp_single_4",
        "ll_intemplate_single_normalized__template_climp_single_5",
        "ll_intemplate_single_pen__template_climp_single_1",
        "ll_intemplate_single_pen__template_climp_single_2",
        "ll_intemplate_single_pen__template_climp_single_3",
        "ll_intemplate_single_pen__template_climp_single_4",
        "ll_intemplate_single_pen__template_climp_single_5",
        "ll_intemplate_compar__template_climp_compar_1",
        "ll_intemplate_compar__template_climp_compar_2",
        "ll_intemplate_compar__template_climp_compar_3",
        "ll_intemplate_compar__template_climp_compar_4",
        "ll_intemplate_compar__template_climp_compar_5",
        "prompting__template_climp_ab_1",
        "prompting__template_climp_ab_2",
        "prompting__template_climp_ab_3",
        "prompting__template_climp_ab_4",
        "prompting__template_climp_ab_5",
        "prompting__template_climp_ab-chat_1",
        "prompting__template_climp_ab-chat_2",
        "prompting__template_climp_ab-chat_3",
        "prompting__template_climp_ab-chat_4",
        "prompting__template_climp_ab-chat_5",
        # Templates asking for 是/非 answers
        # "prompting_yn__template_climp_yn_1",
        # "prompting_yn__template_climp_yn_2",
        # "prompting_yn__template_climp_yn_3",
        # "prompting_yn__template_climp_yn_4",
        # "prompting_yn__template_climp_yn_5",
        # "prompting_yn__template_climp_yn-chat_1",
        # "prompting_yn__template_climp_yn-chat_2",
        # "prompting_yn__template_climp_yn-chat_3",
        # "prompting_yn__template_climp_yn-chat_4",
        # "prompting_yn__template_climp_yn-chat_5",
        # Templates asking for yes/no answers
        "prompting_yn__template_climp_yn-en_1",
        "prompting_yn__template_climp_yn-en_2",
        "prompting_yn__template_climp_yn-en_3",
        "prompting_yn__template_climp_yn-en_4",
        "prompting_yn__template_climp_yn-en_5",
        "prompting_yn__template_climp_yn-en-chat_1",
        "prompting_yn__template_climp_yn-en-chat_2",
        "prompting_yn__template_climp_yn-en-chat_3",
        "prompting_yn__template_climp_yn-en-chat_4",
        "prompting_yn__template_climp_yn-en-chat_5",
    ],
}

approachname_to_officialname = {
    "ll": "LP",
    "ll_normalized": "MeanLP",
    "ll_pen": "PenLP",
    "ll_intemplate_single": "In-template LP",
    "ll_intemplate_single_normalized": "In-template MeanLP",
    "ll_intemplate_single_pen": "In-template PenLP",
    "ll_intemplate_compar": "In-template compar. LP",
    "prompting": "A/B prompting",
    "prompting_yn": "Yes/No prob comp",
}

model_to_abbrev = {
    "Meta-Llama-3-70B": "Llama-3",
    "Meta-Llama-3-70B-Instruct": "Llama-3-Instruct",
    "Mixtral-8x7B-v0.1": "Mixtral",
    "Mixtral-8x7B-Instruct-v0.1": "Mixtral-Instruct",
    # "Qwen1.5-32B": "Qwen1.5",
    # "Qwen1.5-32B-Chat": "Qwen1.5-Chat",
    "Qwen2-57B-A14B": "Qwen2",
    "Qwen2-57B-A14B-Instruct": "Qwen2-Instruct",
    "Yi-1.5-34B": "Yi-1.5",
    "Yi-1.5-34B-Chat": "Yi-1.5-Chat",
    "Smaug-72B-v0.1": "Smaug",
}

data_to_models = {
    "blimp": [
        "Meta-Llama-3-70B_4bit",
        "Meta-Llama-3-70B-Instruct_4bit",
        "Mixtral-8x7B-v0.1_4bit",
        "Mixtral-8x7B-Instruct-v0.1_4bit",
        # "Qwen1.5-32B_4bit",
        # "Qwen1.5-32B-Chat_4bit",
        "Qwen2-57B-A14B_4bit",
        "Qwen2-57B-A14B-Instruct_4bit",
    ],
    "climp": [
        "Meta-Llama-3-70B_4bit",
        "Meta-Llama-3-70B-Instruct_4bit",
        # "Qwen1.5-32B_4bit",
        # "Qwen1.5-32B-Chat_4bit",
        "Yi-1.5-34B_4bit",
        "Yi-1.5-34B-Chat_4bit",
        "Qwen2-57B-A14B_4bit",
        "Qwen2-57B-A14B-Instruct_4bit",
        # "Smaug-72B-v0.1_4bit",
    ],
}

# The models are sorted for the radar chart
data_to_modelssorted = {
    "blimp": [
        "Meta-Llama-3-70B_4bit",
        "Mixtral-8x7B-v0.1_4bit",
        "Qwen2-57B-A14B_4bit",
        "Meta-Llama-3-70B-Instruct_4bit",
        "Mixtral-8x7B-Instruct-v0.1_4bit",
        "Qwen2-57B-A14B-Instruct_4bit",
    ],
    "climp": [
        "Meta-Llama-3-70B_4bit",
        "Yi-1.5-34B_4bit",
        "Qwen2-57B-A14B_4bit",
        "Meta-Llama-3-70B-Instruct_4bit",
        "Yi-1.5-34B-Chat_4bit",
        "Qwen2-57B-A14B-Instruct_4bit",
    ],
}

data_to_phenomenon_to_abbrev = {
    "blimp": {
        # Morphology
        "anaphor_agreement": "An. agr.",
        "determiner_noun_agreement": "D-n agr.",
        "irregular_forms": "Irregular",
        "subject_verb_agreement": "S-v agr.",
        # Syntax
        "argument_structure": "Arg. str.",
        "ellipsis": "Ellipsis",
        "filler_gap_dependency": "F-gap",
        "island_effects": "Island",
        # Semantics
        "npi_licensing": "NPI",
        "quantifiers": "Quantifiers",
        # Syn. & Sem.
        "binding": "Binding",
        "control_raising": "Ctrl. Rais.",
    },
    "climp": {
        "anaphor_agreement": "An. agr.",
        "binding": "Binding",
        "ba_construction": "ba constr.",  # bˇa
        "coverb": "Coverb",
        "head_final": "NP head",
        "classifier": "Classif.",
        "filler_gap_dependency": "F-gap",
        "passive": "Passive",
        "verb_complement": "V compl.",
    },
}
